#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  2 14:40:13 2023

@author: zekibestia
"""

class Objeto(object):
    def __init__(self,Sigma):
        global next_
        super(automata,self__init__())
        self.A = Sigma
        self.Q = { next_ }
        self.s = next_
        self.F = {}
        self.p = {}
        next_ +=1
        # Eliminar las transiciones lambda
        self.lista_Q=[]
        self.cnjto= []
        self.ddd = []
        
def union_c(self,otro):
    global next_
    self.P=self.P.union(otro.P)
    self.p=self.P.union(
        {produccion((next_,'#',self.s)),
         produccion((next_,'#',otro.s)),...})
    self.Q = self.Q.union(otro.Q)
    self.Q=self.Q.union({next_})
    self.F=self.F.union(otro.F)
    self.s=next_
    next_+=1
    
def concatena_c(self,otro):
    self.Q=self.P.union(otro.Q)
    self.P=self.P.union(otro.P)
    for p in self.F:
        self.P.add(produccion((p,'#',otro.s)))
    self.F=otro.F
    
def vacio(self):
    self.Q={self.s}
    self.F={}
    self.P={}
def cadena_vacia(self):
    self.Q={self.s}
    self.F={self.s}
    self.P={}
    
global next_
next_=1
m1=automata('abc')
m1.unitario('a')
m2=automata('abc')
m2.unitario('b')
m1.union_c(m2)
m3=automata('abc')
m3.unitario('c')
m3.estrella()
m1.concatena_c(m3)
m1.ver()
'''
Lo que me tiene que arrojar en consola es lo siguiente:
    Automata
    ======>
    Estados : {q1,q2,q3,q4,q5,q6,q7,q8}
    Inicial: q5
    Aceptacion: {q8}
    Transiciones: {(q6,c,q7),
                   (q2,λ,q8),
                   (q5,λ,q1),
                   (q3,b,q4),
                   (q7,λ,q8),
                   (q1,a,q2),
                   (q8,λ,q6),
                   (q5,λ,q3),
                   (q4,λ,q8)}
    ======>
'''
        
    